### ISSUE TITLE
styles enforced through migration

### ISSUE THREAD

**Issue by yomed** [marko-js/marko-migrate#10]
While I was migrating some projects, I noticed that the migration tool enforces certain stylistic choices such as max line width, and `<component/>` instead of `<component />` (and likely more). These are fairly minor, and I was able to easily fix them in smaller projects. But for larger projects, it would be much more tedious. For choices like these, is there any sense in trying to detect styles before forcing them? I.e. don't enforce max line width by default. I'm not sure how much work is worth putting into a transient package like this.

**Comment by patrick-steele-idem** [comment]
We should update [marko-prettyprint](https://github.com/marko-js/marko-prettyprint) to support more formatting options. Currently, `marko-prettyprint` only allows the syntax and  the indent string to be specified (e.g. `'  '` vs `'\t'`). `marko-migrate` should allow `marko-prettyprint` options to be provided.

Once we update `marko-prettyprint` you can simply reformat all of the Marko templates in your project based on your preferences. On a related note, the PR to integrate `marko-prettyprint` with `atom-beautify` should land soon: https://github.com/Glavin001/atom-beautify/pull/956

**Comment by yomed** [comment]
Closing per the `marko-prettyprint` updates.
