### ISSUE TITLE
Macros called without invoke and spaces

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/marko-migrate#17]
It looks like our testing is being done using `<invoke function="helper"/>` but there are users doing the following:

``` xml
${ helper() }
<def name="helper">
    <div>Hello!</div>
</div>
```

which should migrate to 

``` xml
<helper/>
<macro helper()>
    <div>Hello!</div>
</macro>
```

**Comment by patrick-steele-idem** [comment]
The issue here is that the macro is being invoked before it is declared. Spaces are being handled just fine. The amount of work required to fix the ordering is likely no worth it so closing this issue.
