### ISSUE TITLE
var reference shorthand not transformed inside `for` attribute

### ISSUE THREAD

**Issue by yomed** [marko-js/marko-migrate#2]
I had a Marko v3 template like this:

```
<for each="radio in data.model">
        <input id="radio-$radio.prefix" w-onclick="handleRadioSelect" type="radio"/>
        <label for="radio-$radio.prefix" class="radio-label">$radio.label</label>
</for>
```

The migration tool correctly mapped all the `radio` references like `radio-${radio.prefix}`, but not the one inside the `label` `for` attribute.

**Comment by patrick-steele-idem** [comment]
Thanks for reporting the problem. Fixed! `marko-migrate@1.0.8`
